e-learning/src/Entity/FormateurRequest.php
<?php

namespace App\Entity;

use App\Repository\FormateurRequestRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormateurRequestRepository::class)]
class FormateurRequest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $accepted = false;

    #[ORM\Column]
    private ?bool $treated = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $requested_at = null;
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $motivation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pdfFilename = null;

    public function getPdfFilename(): ?string
    {
        return $this->pdfFilename;
    }

    public function setPdfFilename(?string $pdfFilename): static
    {
        $this->pdfFilename = $pdfFilename;
        return $this;
    }
    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $experience = null;
    #[ORM\ManyToOne(inversedBy: 'formateurRequests')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function __construct()
    {
        $this->accepted = false;
        $this->treated = false;
        $this->requested_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isAccepted(): ?bool
    {
        return $this->accepted;
    }

    public function setAccepted(bool $accepted): static
    {
        $this->accepted = $accepted;
        return $this;
    }

    public function isTreated(): ?bool
    {
        return $this->treated;
    }

    public function setTreated(bool $treated): static
    {
        $this->treated = $treated;
        return $this;
    }

    public function getRequestedAt(): ?\DateTimeImmutable
    {
        return $this->requested_at;
    }

    public function setRequestedAt(\DateTimeImmutable $requested_at): static
    {
        $this->requested_at = $requested_at;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }
    public function getMotivation(): ?string
    {
        return $this->motivation;
    }

    public function setMotivation(?string $motivation): static
    {
        $this->motivation = $motivation;
        return $this;
    }



    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(?int $experience): static
    {
        $this->experience = $experience;
        return $this;
    }



}

e-learning/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Enum\OrderStatus;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    // #[ORM\Column]
    // private ?bool $isVerified = null;

    //#[ORM\Column(length: 255 , nullable: true)]
    //private ?string $roleType = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $formateurInfo = null;
    /**
     * @var Collection<int, Formation>
     */
    #[ORM\OneToMany(targetEntity: Formation::class, mappedBy: 'formateur')]
    private Collection $formations;

    #[ORM\Column]
    private bool $isVerified = false;

    /**
     * @var Collection<int, FormateurRequest>
     */
    #[ORM\OneToMany(targetEntity: FormateurRequest::class, mappedBy: 'user')]
    private Collection $formateurRequests;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Formateur $formateur = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Panier $panier = null;

    /**
     * @var Collection<int, Commande>
     */
    #[ORM\OneToMany(targetEntity: Commande::class, mappedBy: 'user')]
    private Collection $commandes;

    public function __construct()
    {
        $this->formations = new ArrayCollection();
        $this->formateurRequests = new ArrayCollection();
        $this->roles = ['ROLE_USER'];
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */

    public function setRoles(array $roles): self
    {
        // Guarantee every user has ROLE_USER
        if (!in_array('ROLE_USER', $roles)) {
            $roles[] = 'ROLE_USER';
        }

        $this->roles = array_unique($roles);

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    // public function isVerified(): ?bool
    // {
    //     return $this->isVerified;
    // }

    // public function setIsVerified(bool $isVerified): static
    // {
    //     $this->isVerified = $isVerified;

    //     return $this;
    // }
/*
    public function getRoleType(): ?string
    {
        return $this->roleType;
    }

    public function setRoleType(string $roleType): static
    {
        $this->roleType = $roleType;

        return $this;
    }
*/
    public function getFormateurInfo(): ?string
    {
        return $this->formateurInfo;
    }

    public function setFormateurInfo(string $formateurInfo): static
    {
        $this->formateurInfo = $formateurInfo;

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
   /* public function getFormations(): Collection
    {
        return $this->formations;
    }*/

   /* public function addFormation(Formation $formation): static
    {
        if (!$this->formations->contains($formation)) {
            $this->formations->add($formation);
            $formation->setFormateur($this);
        }

        return $this;
    }*/
/*
    public function removeFormation(Formation $formation): static
    {
        if ($this->formations->removeElement($formation)) {
            // set the owning side to null (unless already changed)
            if ($formation->getFormateur() === $this) {
                $formation->setFormateur(null);
            }
        }

        return $this;
    }*/

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, FormateurRequest>
     */
    public function getFormateurRequests(): Collection
    {
        return $this->formateurRequests;
    }

    public function addFormateurRequest(FormateurRequest $formateurRequest): static
    {
        if (!$this->formateurRequests->contains($formateurRequest)) {
            $this->formateurRequests->add($formateurRequest);
            $formateurRequest->setUser($this);
        }

        return $this;
    }

    public function removeFormateurRequest(FormateurRequest $formateurRequest): static
    {
        if ($this->formateurRequests->removeElement($formateurRequest)) {
            // set the owning side to null (unless already changed)
            if ($formateurRequest->getUser() === $this) {
                $formateurRequest->setUser(null);
            }
        }

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(Formateur $formateur): static
    {
        // set the owning side of the relation if necessary
        if ($formateur->getUser() !== $this) {
            $formateur->setUser($this);
        }

        $this->formateur = $formateur;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(Panier $panier): static
    {
        // set the owning side of the relation if necessary
        if ($panier->getUser() !== $this) {
            $panier->setUser($this);
        }

        $this->panier = $panier;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    public function hasPurchasedFormation(Formation $formation): bool
{
    foreach ($this->getCommandes() as $commande) {
        if ($commande->getStatut() === OrderStatus::PAID && $commande->getPanier()) {
            foreach ($commande->getPanier()->getProduitChoisis() as $produitChoisi) {
                if ($produitChoisi->getProduit() instanceof Formation && $produitChoisi->getProduit()->getId() === $formation->getId()) {
                    return true;
                }
            }
        }
    }
    return false;
}

public function hasPurchasedBook(Book $book): bool
{
    foreach ($this->getCommandes() as $commande) {
        if ($commande->getStatut() === OrderStatus::PAID && $commande->getPanier()) {
            foreach ($commande->getPanier()->getProduitChoisis() as $produitChoisi) {
                if ($produitChoisi->getProduit() instanceof Book && $produitChoisi->getProduit()->getId() === $book->getId()) {
                    return true;
                }
            }
        }
    }
    return false;
}


}

e-learning/templates/admin_roles/formateur_requests.html.twig
{# templates/admin/formateur_requests.html.twig #}

{% extends 'dashboard/dashboardAdmin.html.twig' %}

{% block title %}Gestion des demandes formateurs{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="mb-4">Demandes pour devenir formateur</h1>

        {# Flash messages #}
        {% for type in ['success', 'info', 'warning'] %}
            {% for message in app.flashes(type) %}
                <div class="alert alert-{{ type }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endfor %}

        <div class="card shadow-sm border-0">
            <div class="card-body p-0">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                    <tr>
                        <th>Utilisateur</th>
                        <th>Email</th>
                        <th>Motivation</th>
                        <th>Expérience</th>
                        <th>Date de demande</th>
                        <th>CV</th>
                        <th>Statut</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for request in requests %}
                        <tr>
                            <td>{{ request.user.firstname }} {{ request.user.lastname }}</td>
                            <td>{{ request.user.email }}</td>
                            <td>{{ request.motivation }}</td>
                            <td>{{ request.experience }}</td>
                            <td>{{ request.requestedAt ? request.requestedAt|date('d/m/Y H:i') : 'N/A' }}</td>
                            <td>
                                {% if request.pdfFilename %}
                                    <a href="{{ asset('uploads/pdfs/' ~ request.pdfFilename) }}" target="_blank" class="text-decoration-none">
                                        Voir PDF
                                    </a>
                                {% else %}
                                    <span class="text-muted">N/A</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if not request.treated %}
                                    <span class="badge bg-warning text-dark">En attente</span>
                                {% elseif request.accepted %}
                                    <span class="badge bg-success">Acceptée</span>
                                {% else %}
                                    <span class="badge bg-danger">Refusée</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if not request.treated %}
                                    <form method="post" action="{{ path('admin_formateur_accept', {id: request.id}) }}" class="d-inline">
                                        <button
                                                class="btn btn-success btn-sm"
                                                type="submit"
                                                onclick="return confirm('Accepter cette demande ?')"
                                        >
                                            Accepter
                                        </button>
                                    </form>
                                    <form method="post" action="{{ path('admin_formateur_refuse', {id: request.id}) }}" class="d-inline ms-2">
                                        <button
                                                class="btn btn-danger btn-sm"
                                                type="submit"
                                                onclick="return confirm('Refuser cette demande ?')"
                                        >
                                            Refuser
                                        </button>
                                    </form>
                                {% else %}
                                    <em class="text-muted">Aucune action disponible</em>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="8" class="text-center text-muted">Aucune demande trouvée.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

e-learning/templates/admin_roles/user_add.html.twig
{% extends 'dashboard/dashboardAdmin.html.twig' %}

{% block title %}Add New User{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h1 class="h3">➕ Add a New User</h1>
            <a href="{{ path('dashboard_path') }}" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Go back
            </a>
        </div>

        <div class="card shadow-sm border-0">
            <div class="card-body">
                {{ form_start(form, {'attr': {'class': 'needs-validation'}}) }}

                <div class="mb-3">
                    {{ form_row(form.firstName) }}
                </div>
                <div class="mb-3">
                    {{ form_row(form.lastName) }}
                </div>
                <div class="mb-3">
                    {{ form_row(form.email) }}
                </div>

                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-success">
                        <i class="bi bi-person-plus"></i> Add User
                    </button>
                </div>

                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

e-learning/templates/admin_roles/user_list.html.twig
{% extends 'dashboard/dashboardAdmin.html.twig' %}

{% block title %}User List{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h1 class="h3">👥 All Users</h1>
            <a href="{{ path('dashboard_path') }}" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Go back
            </a>
        </div>

        <div class="card shadow-sm border-0">
            <div class="card-body">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Roles</th>
                        <th>State</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ user.firstName }} {{ user.lastName }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                    {% set priority = ['ROLE_ADMIN', 'ROLE_FORMATEUR', 'ROLE_USER'] %}
                                    {% set highestRole = null %}

                                    {% for role in priority %}
                                        {% if role in user.roles and highestRole is null %}
                                            {% set highestRole = role %}
                                        {% endif %}
                                    {% endfor %}

                                    {% if highestRole %}
                                        <span class="badge
            {% if highestRole == 'ROLE_ADMIN' %} bg-danger
            {% elseif highestRole == 'ROLE_FORMATEUR' %} bg-info text-dark
            {% else %} bg-secondary
            {% endif %}">
            {{ highestRole|replace({'ROLE_': ''})|lower|capitalize }}
        </span>
                                    {% endif %}

                            </td>

                            <td>
                                {% if user.verified %}
                                    <span class="badge bg-success">Verified</span>
                                {% else %}
                                    <span class="badge bg-danger">Not verified</span>
                                {% endif %}
                            </td>

                            <td>

                                {% if user.email != app.user.email %}
                                    {{ include('partials/_delete_user_form.html.twig', { user: user }) }}
                                {% else %}
                                    <span class="text-muted" title="Vous ne pouvez pas supprimer votre propre compte">—</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6" class="text-center text-muted">No users found.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}